# Example secrets file for Streamlit apps in this repository.
# Copy this file to `.streamlit/secrets.toml` and add your own Hugging Face API key.
# Never commit your real secrets to a public repository.

HF_API_KEY = "your_hf_token_here"  # Replace with your personal Hugging Face API key

# Optional: You can change the model repo below to try other supported models.
HF_MODEL_REPO = "mistralai/Mistral-7B-Instruct-v0.2"